# Generated by Django 4.2.22 on 2026-09-27 20:51

from django.db import migrations, models

import dict_field.models
import django_dto_field.fields.binary
import django_dto_field.fields.char
import django_dto_field.fields.json


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataclassModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    django_dto_field.fields.char.DTOCharField(
                        max_length=1000, schema=dict_field.models.UserDTO
                    ),
                ),
                (
                    "binary",
                    django_dto_field.fields.binary.DTOBinaryField(
                        schema=dict_field.models.UserDTO
                    ),
                ),
                (
                    "json",
                    django_dto_field.fields.json.DTOJSONField(
                        schema=dict_field.models.UserDTO
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DictModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    django_dto_field.fields.char.DTOCharField(
                        blank=True, default=dict, max_length=1000
                    ),
                ),
                (
                    "binary",
                    django_dto_field.fields.binary.DTOBinaryField(
                        blank=True, default=dict
                    ),
                ),
                (
                    "json",
                    django_dto_field.fields.json.DTOJSONField(blank=True, default=dict),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NullableModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    django_dto_field.fields.char.DTOCharField(
                        blank=True,
                        max_length=1000,
                        null=True,
                        schema=dict_field.models.UserDTO,
                    ),
                ),
                (
                    "binary",
                    django_dto_field.fields.binary.DTOBinaryField(
                        blank=True, null=True, schema=dict_field.models.UserDTO
                    ),
                ),
                (
                    "json",
                    django_dto_field.fields.json.DTOJSONField(
                        blank=True, null=True, schema=dict_field.models.UserDTO
                    ),
                ),
            ],
        ),
    ]
