# Generated by Django 4.2.22 on 2026-09-29 19:33

from django.db import migrations, models

import dict_field.adapters
import django_dto_field.fields.binary
import django_dto_field.fields.char
import django_dto_field.fields.json


class Migration(migrations.Migration):
    dependencies = [
        ("dict_field", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    django_dto_field.fields.char.DTOCharField(
                        adapter=dict_field.adapters.MessageAdapter,
                        max_length=1000,
                        schema=dict_field.adapters.MessageSchema,
                    ),
                ),
                (
                    "binary",
                    django_dto_field.fields.binary.DTOBinaryField(
                        adapter=dict_field.adapters.MessageAdapter,
                        schema=dict_field.adapters.MessageSchema,
                    ),
                ),
                (
                    "json",
                    django_dto_field.fields.json.DTOJSONField(
                        adapter=dict_field.adapters.MessageAdapter,
                        schema=dict_field.adapters.MessageSchema,
                    ),
                ),
            ],
        ),
    ]
